//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreelancerModStudio.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreelancerModStudio.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About {0}.
        /// </summary>
        internal static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Version {0}.
        /// </summary>
        internal static string AboutVersion {
            get {
                return ResourceManager.GetString("AboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error List.
        /// </summary>
        internal static string ErrorListText {
            get {
                return ResourceManager.GetString("ErrorListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save &apos;{0}&apos;?.
        /// </summary>
        internal static string FileCloseSave {
            get {
                return ResourceManager.GetString("FileCloseSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на General.
        /// </summary>
        internal static string FileDefaultCategory {
            get {
                return ResourceManager.GetString("FileDefaultCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на INI-Files (*.ini)|*.ini;*.INI|FLMM Backup INI-Files (*.ini.flmmbak)|*.ini.flmmbak|All Files (*.*)|*.*.
        /// </summary>
        internal static string FileDialogFilter {
            get {
                return ResourceManager.GetString("FileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        internal static string FileEditorColumnName {
            get {
                return ResourceManager.GetString("FileEditorColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type.
        /// </summary>
        internal static string FileEditorColumnType {
            get {
                return ResourceManager.GetString("FileEditorColumnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No entries existing....
        /// </summary>
        internal static string FileEditorEmpty {
            get {
                return ResourceManager.GetString("FileEditorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New File.
        /// </summary>
        internal static string FileEditorNewFile {
            get {
                return ResourceManager.GetString("FileEditorNewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open Solar Archetype INI ({0}).
        /// </summary>
        internal static string FileEditorOpenSolarArch {
            get {
                return ResourceManager.GetString("FileEditorOpenSolarArch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &amp;Save {0}.
        /// </summary>
        internal static string FileEditorSave {
            get {
                return ResourceManager.GetString("FileEditorSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save {0} &amp;as....
        /// </summary>
        internal static string FileEditorSaveAs {
            get {
                return ResourceManager.GetString("FileEditorSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The file &apos;{0}&apos; could not be opened..
        /// </summary>
        internal static string FileErrorOpen {
            get {
                return ResourceManager.GetString("FileErrorOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The file &apos;{0}&apos; cannot be opened. Do you want to remove it from the Recent list?.
        /// </summary>
        internal static string FileErrorOpenRecent {
            get {
                return ResourceManager.GetString("FileErrorOpenRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The file &apos;{0}&apos; could not be saved. Please check if it is opened in another application or if the file is marked as read-only..
        /// </summary>
        internal static string FileErrorSave {
            get {
                return ResourceManager.GetString("FileErrorSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid INI Property.
        /// </summary>
        internal static string InvalidIniPropertyNotificationCaption {
            get {
                return ResourceManager.GetString("InvalidIniPropertyNotificationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} was given an invalid type. It expects: {1}
        ///
        ///This warning can be disabled in the options menu..
        /// </summary>
        internal static string InvalidIniPropertyNotificationText {
            get {
                return ResourceManager.GetString("InvalidIniPropertyNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The entered mod homepage is invalid..
        /// </summary>
        internal static string ModInvalidHomepage {
            get {
                return ResourceManager.GetString("ModInvalidHomepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The mod name must not contain the following chars: / ? : &amp; * &quot; &lt; &gt; | # %
        ///
        ///Please enter a valid name..
        /// </summary>
        internal static string ModInvalidNameChars {
            get {
                return ResourceManager.GetString("ModInvalidNameChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The mod path must not contain the following chars: / ? : &amp; * &quot; &lt; &gt; | # %
        ///
        ///Please enter a valid name..
        /// </summary>
        internal static string ModInvalidPathChars {
            get {
                return ResourceManager.GetString("ModInvalidPathChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mod{0}.
        /// </summary>
        internal static string ModNewName {
            get {
                return ResourceManager.GetString("ModNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Properties.
        /// </summary>
        internal static string PropertiesText {
            get {
                return ResourceManager.GetString("PropertiesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The settings file &apos;{0}&apos; could not be loaded..
        /// </summary>
        internal static string SettingsLoadException {
            get {
                return ResourceManager.GetString("SettingsLoadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The settings file &apos;{0}&apos; could not be saved..
        /// </summary>
        internal static string SettingsSaveException {
            get {
                return ResourceManager.GetString("SettingsSaveException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Solution Explorer.
        /// </summary>
        internal static string SolutionExplorerText {
            get {
                return ResourceManager.GetString("SolutionExplorerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open {0}....
        /// </summary>
        internal static string SystemPresenterOpen {
            get {
                return ResourceManager.GetString("SystemPresenterOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Angles: .
        /// </summary>
        internal static string SystemPresenterTrackedAngles {
            get {
                return ResourceManager.GetString("SystemPresenterTrackedAngles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Distance: .
        /// </summary>
        internal static string SystemPresenterTrackedDistance {
            get {
                return ResourceManager.GetString("SystemPresenterTrackedDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The template file &apos;{0}&apos; could not be loaded..
        /// </summary>
        internal static string TemplateLoadException {
            get {
                return ResourceManager.GetString("TemplateLoadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &amp;Abort.
        /// </summary>
        internal static string UpdatesAbortButton {
            get {
                return ResourceManager.GetString("UpdatesAbortButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There are new updates for {0} available. Do you want to download them now?.
        /// </summary>
        internal static string UpdatesAviableDescription {
            get {
                return ResourceManager.GetString("UpdatesAviableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Updates Found.
        /// </summary>
        internal static string UpdatesAviableHeader {
            get {
                return ResourceManager.GetString("UpdatesAviableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} is now checking for updates....
        /// </summary>
        internal static string UpdatesCheckingDescription {
            get {
                return ResourceManager.GetString("UpdatesCheckingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Checking for Updates.
        /// </summary>
        internal static string UpdatesCheckingHeader {
            get {
                return ResourceManager.GetString("UpdatesCheckingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &amp;Download.
        /// </summary>
        internal static string UpdatesDownloadButton {
            get {
                return ResourceManager.GetString("UpdatesDownloadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The updates were successfully downloaded. You have to restart {0} in order to install the updates..
        /// </summary>
        internal static string UpdatesDownloadedDescription {
            get {
                return ResourceManager.GetString("UpdatesDownloadedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download Complete.
        /// </summary>
        internal static string UpdatesDownloadedHeader {
            get {
                return ResourceManager.GetString("UpdatesDownloadedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An Error occured while downloading. Please check your internet connection and make sure that your firewall does not block {0}.
        ///
        ///If that problem persists, download and install the update manually..
        /// </summary>
        internal static string UpdatesDownloadException {
            get {
                return ResourceManager.GetString("UpdatesDownloadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} is now downloading the new updates....
        /// </summary>
        internal static string UpdatesDownloadingDescription {
            get {
                return ResourceManager.GetString("UpdatesDownloadingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Downloading Updates.
        /// </summary>
        internal static string UpdatesDownloadingHeader {
            get {
                return ResourceManager.GetString("UpdatesDownloadingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} of {1} MB.
        /// </summary>
        internal static string UpdatesDownloadSpeed {
            get {
                return ResourceManager.GetString("UpdatesDownloadSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &amp;Finish.
        /// </summary>
        internal static string UpdatesFinishButton {
            get {
                return ResourceManager.GetString("UpdatesFinishButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}% - Software Update.
        /// </summary>
        internal static string UpdatesFormDownloadText {
            get {
                return ResourceManager.GetString("UpdatesFormDownloadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Software Update.
        /// </summary>
        internal static string UpdatesFormText {
            get {
                return ResourceManager.GetString("UpdatesFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &amp;Hide.
        /// </summary>
        internal static string UpdatesHideButton {
            get {
                return ResourceManager.GetString("UpdatesHideButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &amp;Install.
        /// </summary>
        internal static string UpdatesInstallButton {
            get {
                return ResourceManager.GetString("UpdatesInstallButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &amp;Later.
        /// </summary>
        internal static string UpdatesLaterButton {
            get {
                return ResourceManager.GetString("UpdatesLaterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There are no new updates available. {0} may check periodically for new updates..
        /// </summary>
        internal static string UpdatesNotAviableDescription {
            get {
                return ResourceManager.GetString("UpdatesNotAviableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No Updates Found.
        /// </summary>
        internal static string UpdatesNotAviableHeader {
            get {
                return ResourceManager.GetString("UpdatesNotAviableHeader", resourceCulture);
            }
        }
    }
}
